# Generated by Django 5.2.1 on 2025-05-26 03:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='도시명')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('order', models.IntegerField(default=0, verbose_name='정렬 순서')),
            ],
            options={
                'verbose_name': '도시',
                'verbose_name_plural': '도시',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ImportantFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='중요 요소')),
                ('order', models.IntegerField(default=0, verbose_name='정렬 순서')),
            ],
            options={
                'verbose_name': '중요 요소',
                'verbose_name_plural': '중요 요소',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TransportationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='교통 카테고리')),
                ('order', models.IntegerField(default=0, verbose_name='정렬 순서')),
            ],
            options={
                'verbose_name': '교통 카테고리',
                'verbose_name_plural': '교통 카테고리',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TravelPurpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='여행 목적')),
                ('order', models.IntegerField(default=0, verbose_name='정렬 순서')),
            ],
            options={
                'verbose_name': '여행 목적',
                'verbose_name_plural': '여행 목적',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TravelStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='여행 스타일')),
                ('order', models.IntegerField(default=0, verbose_name='정렬 순서')),
            ],
            options={
                'verbose_name': '여행 스타일',
                'verbose_name_plural': '여행 스타일',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WeatherCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='날씨 카테고리')),
                ('order', models.IntegerField(default=0, verbose_name='정렬 순서')),
            ],
            options={
                'verbose_name': '날씨 카테고리',
                'verbose_name_plural': '날씨 카테고리',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='구/군/읍/면')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('order', models.IntegerField(default=0, verbose_name='정렬 순서')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='travel_input.city', verbose_name='도시')),
            ],
            options={
                'verbose_name': '구/군/읍/면',
                'verbose_name_plural': '구/군/읍/면',
                'ordering': ['city', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TransportationMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='교통 수단')),
                ('order', models.IntegerField(default=0, verbose_name='정렬 순서')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modes', to='travel_input.transportationcategory', verbose_name='교통 카테고리')),
            ],
            options={
                'verbose_name': '교통 수단',
                'verbose_name_plural': '교통 수단',
                'ordering': ['category', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='새로운 여행 계획', max_length=200, verbose_name='일정 제목')),
                ('start_date', models.DateField(verbose_name='시작일')),
                ('end_date', models.DateField(verbose_name='종료일')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='예산')),
                ('notes', models.TextField(blank=True, verbose_name='메모')),
                ('age_group', models.CharField(choices=[('10대', '10대'), ('20대', '20대'), ('30대', '30대'), ('40대', '40대'), ('50대', '50대'), ('60대 이상', '60대 이상')], default='20대', max_length=50, verbose_name='연령대')),
                ('ai_response', models.TextField(blank=True, verbose_name='AI 응답')),
                ('user_feedback', models.TextField(blank=True, verbose_name='사용자 피드백')),
                ('ai_feedback_response', models.TextField(blank=True, verbose_name='AI 피드백 응답')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('city', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='travel_input.city', verbose_name='도시')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='travel_input.district', verbose_name='구/군/읍/면')),
                ('important_factors', models.ManyToManyField(to='travel_input.importantfactor', verbose_name='중요 요소')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
                ('transportation_mode', models.ManyToManyField(to='travel_input.transportationmode', verbose_name='교통 수단')),
                ('travel_purpose', models.ManyToManyField(to='travel_input.travelpurpose', verbose_name='여행 목적')),
                ('travel_style', models.ManyToManyField(to='travel_input.travelstyle', verbose_name='여행 스타일')),
            ],
            options={
                'verbose_name': '여행 일정',
                'verbose_name_plural': '여행 일정',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PreferredWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='선호 날씨')),
                ('order', models.IntegerField(default=0, verbose_name='정렬 순서')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weathers', to='travel_input.weathercategory', verbose_name='날씨 카테고리')),
            ],
            options={
                'verbose_name': '선호 날씨',
                'verbose_name_plural': '선호 날씨',
                'ordering': ['category', 'order', 'name'],
            },
        ),
    ]
