# Generated by Django 5.2.1 on 2025-05-26 03:19

from django.db import migrations

def add_travel_data(apps, schema_editor):
    TravelPurpose = apps.get_model('travel_input', 'TravelPurpose')
    TravelStyle = apps.get_model('travel_input', 'TravelStyle')
    ImportantFactor = apps.get_model('travel_input', 'ImportantFactor')

    # 여행 목적 데이터
    travel_purposes = [
        '휴양/힐링', '관광/탐방', '액티비티/스포츠', '쇼핑', '먹방', '업무/출장', '가족여행', '커플여행', '혼자여행', '친구와 여행'
    ]
    for order, name in enumerate(travel_purposes):
        TravelPurpose.objects.get_or_create(name=name, defaults={'order': order})

    # 여행 스타일 데이터
    travel_styles = [
        '자유여행', '패키지여행', '호캉스', '캠핑/글램핑', '크루즈여행', '기차여행', '도보여행', '자전거여행'
    ]
    for order, name in enumerate(travel_styles):
        TravelStyle.objects.get_or_create(name=name, defaults={'order': order})

    # 중요 요소 데이터
    important_factors = [
        '예산', '이동 시간', '숙소 편의성', '음식', '액티비티 종류', '휴식 가능성', '자연 경관', '문화/역사 유적', '쇼핑 기회', '사진 촬영 명소'
    ]
    for order, name in enumerate(important_factors):
        ImportantFactor.objects.get_or_create(name=name, defaults={'order': order})


class Migration(migrations.Migration):

    dependencies = [
        ('travel_input', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_travel_data),
    ]
