# Generated by Django 5.2.1 on 2025-05-26 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_input', '0002_auto_20250526_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='district',
        ),
    ]
