# Generated by Django 5.2.1 on 2025-05-26 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_input', '0003_remove_schedule_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='액티비티명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
            ],
            options={
                'verbose_name': '액티비티',
                'verbose_name_plural': '액티비티',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='schedule',
            name='activities',
            field=models.ManyToManyField(blank=True, to='travel_input.activity', verbose_name='선호 액티비티'),
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='여행지명')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinations', to='travel_input.city', verbose_name='도시')),
            ],
            options={
                'verbose_name': '여행지',
                'verbose_name_plural': '여행지',
                'ordering': ['city', 'name'],
            },
        ),
        migrations.AddField(
            model_name='schedule',
            name='destinations',
            field=models.ManyToManyField(blank=True, to='travel_input.destination', verbose_name='추천 여행지'),
        ),
    ]
