# Generated by Django 5.2.1 on 2025-05-26 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_input', '0004_activity_schedule_activities_destination_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='notes',
        ),
    ]
