# Generated by Django 5.2.1 on 2025-05-23 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_input', '0020_add_default_destinations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='종료일시'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_date',
            field=models.DateTimeField(verbose_name='시작일시'),
        ),
    ]
