# Generated by Django 5.2.1 on 2025-05-23 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_input', '0021_alter_schedule_end_date_alter_schedule_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='transportation_mode',
            field=models.CharField(blank=True, max_length=255, verbose_name='선호 교통수단'),
        ),
    ]
