# Generated by Django 5.2.1 on 2025-05-26 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_input', '0021_alter_schedule_end_date_alter_schedule_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='place',
            name='category',
        ),
        migrations.DeleteModel(
            name='CultureCategory',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='destination',
        ),
        migrations.AlterUniqueTogether(
            name='groupmember',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='groupmember',
            name='group',
        ),
        migrations.RemoveField(
            model_name='groupmember',
            name='user',
        ),
        migrations.RemoveField(
            model_name='grouptravel',
            name='members',
        ),
        migrations.RemoveField(
            model_name='groupmessage',
            name='group',
        ),
        migrations.RemoveField(
            model_name='groupmessage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='grouptravel',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='grouptravel',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='place',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='transport',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='traveloption',
            name='category',
        ),
        migrations.AlterModelOptions(
            name='importantfactor',
            options={'ordering': ['order', 'name'], 'verbose_name': '중요 요소', 'verbose_name_plural': '중요 요소'},
        ),
        migrations.AlterModelOptions(
            name='travelpurpose',
            options={'ordering': ['order', 'name'], 'verbose_name': '여행 목적', 'verbose_name_plural': '여행 목적'},
        ),
        migrations.AlterModelOptions(
            name='travelstyle',
            options={'ordering': ['order', 'name'], 'verbose_name': '여행 스타일', 'verbose_name_plural': '여행 스타일'},
        ),
        migrations.RemoveField(
            model_name='city',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='event_interest',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='favorite',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='group_type',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='language_support',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='meal_preference',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='mobility_needs',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='participant_info',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='place_info',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='preferred_activities',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='repeat_visitor',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='season',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='transport_info',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='travel_insurance',
        ),
        migrations.AddField(
            model_name='importantfactor',
            name='order',
            field=models.IntegerField(default=0, verbose_name='정렬 순서'),
        ),
        migrations.AddField(
            model_name='travelpurpose',
            name='order',
            field=models.IntegerField(default=0, verbose_name='정렬 순서'),
        ),
        migrations.AddField(
            model_name='travelstyle',
            name='order',
            field=models.IntegerField(default=0, verbose_name='정렬 순서'),
        ),
        migrations.AlterField(
            model_name='city',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='활성화 여부'),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100, verbose_name='도시명'),
        ),
        migrations.AlterField(
            model_name='importantfactor',
            name='name',
            field=models.CharField(max_length=50, verbose_name='중요 요소'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='age_group',
            field=models.CharField(choices=[('10대', '10대'), ('20대', '20대'), ('30대', '30대'), ('40대', '40대'), ('50대', '50대'), ('60대 이상', '60대 이상')], default='20대', max_length=50, verbose_name='연령대'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='ai_feedback_response',
            field=models.TextField(blank=True, verbose_name='AI 피드백 응답'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='ai_response',
            field=models.TextField(blank=True, verbose_name='AI 응답'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end_date',
            field=models.DateField(verbose_name='종료일'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='important_factors',
            field=models.ManyToManyField(to='travel_input.importantfactor', verbose_name='중요 요소'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='notes',
            field=models.TextField(blank=True, verbose_name='메모'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='start_date',
            field=models.DateField(verbose_name='시작일'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='travel_purpose',
            field=models.ManyToManyField(to='travel_input.travelpurpose', verbose_name='여행 목적'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='travel_style',
            field=models.ManyToManyField(to='travel_input.travelstyle', verbose_name='여행 스타일'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='user_feedback',
            field=models.TextField(blank=True, verbose_name='사용자 피드백'),
        ),
        migrations.AlterField(
            model_name='travelpurpose',
            name='name',
            field=models.CharField(max_length=50, verbose_name='여행 목적'),
        ),
        migrations.AlterField(
            model_name='travelstyle',
            name='name',
            field=models.CharField(max_length=50, verbose_name='여행 스타일'),
        ),
        migrations.DeleteModel(
            name='Budget',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Destination',
        ),
        migrations.DeleteModel(
            name='GroupMember',
        ),
        migrations.DeleteModel(
            name='GroupMessage',
        ),
        migrations.DeleteModel(
            name='GroupTravel',
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
        migrations.DeleteModel(
            name='Place',
        ),
        migrations.DeleteModel(
            name='Transport',
        ),
        migrations.DeleteModel(
            name='TravelOption',
        ),
        migrations.DeleteModel(
            name='TravelOptionCategory',
        ),
    ]
