# Generated by Django 5.2.1 on 2025-05-23 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_input', '0022_schedule_transportation_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportationMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='교통수단')),
            ],
            options={
                'verbose_name': '교통수단',
                'verbose_name_plural': '교통수단들',
            },
        ),
        migrations.AlterField(
            model_name='schedule',
            name='transport_info',
            field=models.TextField(blank=True, default='', null=True, verbose_name='교통 정보 상세'),
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='transportation_mode',
        ),
        migrations.AddField(
            model_name='schedule',
            name='transportation_mode',
            field=models.ManyToManyField(blank=True, to='travel_input.transportationmode', verbose_name='선호 교통수단'),
        ),
    ]
