# Generated by Django 5.2.1 on 2025-05-23 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_input', '0023_transportationmode_alter_schedule_transport_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='교통수단 카테고리')),
            ],
            options={
                'verbose_name': '교통수단 카테고리',
                'verbose_name_plural': '교통수단 카테고리들',
            },
        ),
        migrations.AlterModelOptions(
            name='transportationmode',
            options={'ordering': ['category__name', 'name'], 'verbose_name': '교통수단 종류', 'verbose_name_plural': '교통수단 종류들'},
        ),
        migrations.AlterField(
            model_name='transportationmode',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='교통수단 종류'),
        ),
        migrations.AddField(
            model_name='transportationmode',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modes', to='travel_input.transportationcategory', verbose_name='카테고리'),
        ),
    ]
