# Generated by Django 5.2.1 on 2025-05-23 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_input', '0002_create_default_transportation_category'),
        ('travel_input', '0024_transportationcategory_and_more'),
    ]

    operations = [
    ]
