# Generated by Django 5.2.1 on 2025-05-23 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_input', '0025_merge_20250523_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='event_interest',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='group_type',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='language_support',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='meal_preference',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='mobility_needs',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='participant_info',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='place_info',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='preferred_activities',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='season',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='transport_info',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='ai_feedback_response',
            field=models.TextField(blank=True, null=True, verbose_name='AI 개선 제안'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='user_feedback',
            field=models.TextField(blank=True, null=True, verbose_name='사용자 피드백'),
        ),
        migrations.AlterField(
            model_name='transportationmode',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='modes', to='travel_input.transportationcategory', verbose_name='카테고리'),
        ),
    ]
