# Generated by Django 5.2.1 on 2025-05-23 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_input', '0026_remove_schedule_event_interest_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='repeat_visitor',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='travel_insurance',
        ),
    ]
