# Generated by Django 5.2.1 on 2025-05-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_input', '0027_remove_schedule_repeat_visitor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='preferred_weather',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='선호 날씨'),
        ),
    ]
