# Generated by Django 5.2.1 on 2025-05-23 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_input', '0028_schedule_preferred_weather'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferredWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='날씨 종류')),
                ('order', models.IntegerField(default=0, verbose_name='정렬 순서')),
            ],
            options={
                'verbose_name': '선호 날씨',
                'verbose_name_plural': '선호 날씨',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='schedule',
            name='preferred_weather',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='travel_input.preferredweather', verbose_name='선호 날씨'),
        ),
    ]
