# Generated by Django 5.2.1 on 2025-05-23 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_input', '0029_preferredweather_alter_schedule_preferred_weather'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='날씨 카테고리')),
                ('order', models.IntegerField(default=0, verbose_name='정렬 순서')),
            ],
            options={
                'verbose_name': '날씨 카테고리',
                'verbose_name_plural': '날씨 카테고리',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='preferredweather',
            options={'ordering': ['category__order', 'order', 'name'], 'verbose_name': '선호 날씨', 'verbose_name_plural': '선호 날씨'},
        ),
        migrations.AddField(
            model_name='preferredweather',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weathers', to='travel_input.weathercategory', verbose_name='날씨 카테고리'),
        ),
    ]
